//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfColegio.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno_Curso
    {
        public int idAlumno { get; set; }
        public int idCurso { get; set; }
        public int nota { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Curso Curso { get; set; }
    }
}
