//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfColegio.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public Curso()
        {
            this.Alumno_Curso = new HashSet<Alumno_Curso>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public System.DateTime inicio { get; set; }
        public System.DateTime fin { get; set; }
        public int duracion { get; set; }
    
        public virtual ICollection<Alumno_Curso> Alumno_Curso { get; set; }
    }
}
